--- #YAML:1.0
name: Test-Strict
version: 0.03
license: perl
distribution_type: module
requires:
  Devel::Cover: 0.43
  File::Find: 0.01
  File::Spec: 0.01
  FindBin: 0.01
  Test::Builder: 0.01
  Test::Simple: 0.47
recommends: {}
build_requires:
  File::Temp: 0.01
  Test::Pod: 0.01
conflicts: {}
dynamic_config: 0
provides:
  Test::Strict:
    file: lib/Test/Strict.pm
    version: 0.03
generated_by: Module::Build version 0.21
