---
abstract: 'Check syntax, presence of use strict; and test coverage'
author:
  - 'Pierre Denis <pdenis@cpan.org>'
build_requires:
  File::Temp: '0.01'
  Test::More: '1.00'
configure_requires:
  ExtUtils::MakeMaker: '6.64'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Strict
no_index:
  directory:
    - t
    - inc
requires:
  Devel::Cover: '0.43'
  File::Find: '0.01'
  File::Spec: '0.01'
  File::Temp: '0.01'
  FindBin: '0.01'
  Test::Builder: '0.01'
resources:
  repository: http://github.com/szabgab/Test-Strict.git
version: '0.25'
x_contributors:
  - 'Gabor Szabo <szabgab@cpan.org>'
  - 'Peter Vereshagin <veresc@cpan.org>'
  - 'Graham Knop <haarg@cpan.org>'
