---
name: Test-Strict
version: 0.10
author:
  - 'Pierre Denis, C<< <pierre@itrelease.net> >>.'
abstract: 'Check syntax, presence of use strict; and test coverage'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Devel::Cover: 0.43
  File::Find: 0.01
  File::Spec: 0.01
  FindBin: 0.01
  Test::Builder: 0.01
  Test::Simple: 0.47
build_requires:
  File::Temp: 0.01
  Test::Pod: 0.01
dynamic_config: 0
provides:
  Test::Strict:
    file: lib/Test/Strict.pm
    version: 0.10
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
